"""empty message

Revision ID: 3f2b89969c67
Revises: a2d92501f1f7
Create Date: 2025-05-12 23:20:49.018561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2b89969c67'
down_revision = 'a2d92501f1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        # Drop the old column
        batch_op.drop_column('completed_at')

        # Add a new column as DateTime
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        # Drop the DateTime column
        batch_op.drop_column('completed_at')

        # Add it back as VARCHAR (string)
        batch_op.add_column(sa.Column('completed_at', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
